import { StyleSheet } from '@react-pdf/renderer';

export const styles = StyleSheet.create({
    page: {
        backgroundColor: "#E4E4E4",
        padding: 30,
    },
    title: {
        border: "1px solid #000",
        width: "100%",
        padding: 3,
        marginBottom: 20,
        textAlign: "center",
        fontWeight: "bolder",
        fontSize: "24px",
    },
    nombreYApellido: {
        fontSize: "12px",
        fontWeight: "light",
        marginBottom: 20,
    },
    nombre: {
        borderBottom: "1px solid #000",
        width: "100%",
        fontSize: "14px",
    },
    cargoQueDesempeña: {
        fontSize: "12px",
        fontWeight: "light",
        marginBottom: 20,
    },
    cargo: {
        borderBottom: "1px solid #000",
        width: "100%",
        fontSize: "14px",
    },
    articulo: {
        width: "100%",
        border: "1px solid #000",
        padding: "20px",
        fontSize: "12px",
        display: "flex",
        flexDirection: "row",
        flexWrap: "wrap",
        lineHeight: "1px",
    },
    primeraLinea: {
        marginBottom: 10,
    },
    dia: {
        borderBottom: "1px solid #000",
        width: "27%",
        textAlign: "center",
        paddingLeft: 7,
        paddingRight: 7,
        marginRight: 5,
    },
    mes: {
        borderBottom: "1px solid #000",
        width: "27%",
        textAlign: "center",
        paddingLeft: 7,
        paddingRight: 7,
        marginLeft: 5,
        marginRight: 5,
    },
    año: {
        borderBottom: "1px solid #000",
        width: "16.5%",
        textAlign: "center",
        paddingLeft: 7,
        paddingRight: 7,
        marginLeft: 5,
    },
    fechaContainer: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        width: "25%",
    },
    fechaCompleta: {
        textAlign: "center",
        width: "100%",
        marginTop: 10,
    },
    fechaTitulo: {
        width: "100%",
        borderTop: "1px solid #000",
        padding: "5px",
        textAlign: "center",
        fontSize: "10px",
    },
    saludo: {
        marginTop: 10,
        marginLeft: 5,
    },
    solicitanteContainer: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        width: "30%",
        marginLeft: 40,
        marginTop: 50,
    },
    solicitanteFirmaTitulo: {
        width: "100%",
        borderTop: "1px solid #000",
        padding: "5px",
        textAlign: "center",
        fontSize: "10px",
    },
    selloAutoridadContainer: {
        width: "100%",
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-between",
        marginTop: 50,
    },
    selloContainer: {
        width: "35%",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
    },
    autoridadSelloTitulo: {
        width: "100%",
        borderTop: "1px solid #000",
        padding: "5px",
        textAlign: "center",
        fontSize: "10px",
    },
    autoridadContainer: {
        width: "35%",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
    },
    autoridadFirmaTitulo: {
        width: "100%",
        borderTop: "1px solid #000",
        padding: "5px",
        textAlign: "center",
        fontSize: "10px",
    },
});